# TaxJar WooCommerce Plugin Release Pipeline
# Deploys new versions to GitHub and WordPress.org

env:
  VERSION: ""

steps:
  # Stage 1: Detect Version
  - label: ":mag: Detect New Version"
    key: "detect-version"
    command: |
      .buildkite/scripts/release-tool detect-version

      if buildkite-agent meta-data exists "SKIP_RELEASE" 2>/dev/null; then
        echo "+++ Version already deployed - skipping release"
        buildkite-agent annotate "Version already exists on WordPress.org" --style "info"
        exit 0
      fi
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          mount-buildkite-agent: true
          always-pull: true
    timeout_in_minutes: 5

  - wait

  # Stage 2: Full Test Suite
  - label: ":test_tube: Full Test Suite"
    key: "test-suite"
    depends_on: "detect-version"
    command: |
      echo "+++ Running full test suite on master"
      buildkite-agent pipeline upload .buildkite/pipeline.yml
    agents:
      queue: docker
    timeout_in_minutes: 60

  - wait

  # Stage 3: GitHub Release
  - label: ":github: Create GitHub Release"
    key: "github-release"
    depends_on: "test-suite"
    command: |
      if [[ -z "$VERSION" ]]; then
        export VERSION=$(buildkite-agent meta-data get "release-version")
      fi
      .buildkite/scripts/release-tool github-release
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          mount-buildkite-agent: true
          always-pull: true
          environment:
            - GITHUB_TOKEN
    timeout_in_minutes: 10

  # Stage 4: SVN Deploy
  - label: ":package: Deploy to WordPress.org"
    key: "svn-deploy"
    depends_on: "github-release"
    command: |
      if [[ -z "$VERSION" ]]; then
        export VERSION=$(buildkite-agent meta-data get "release-version")
      fi
      .buildkite/scripts/release-tool svn-deploy
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          mount-buildkite-agent: true
          always-pull: true
          environment:
            - WORDPRESS_SVN_USERNAME
            - WORDPRESS_SVN_PASSWORD
    timeout_in_minutes: 15

  # Stage 5: Verify
  - label: ":mag: Verify Release"
    key: "verify"
    depends_on: "svn-deploy"
    command: |
      if [[ -z "$VERSION" ]]; then
        export VERSION=$(buildkite-agent meta-data get "release-version")
      fi

      echo "--- Waiting for WordPress.org to update"
      sleep 30

      PLUGIN_URL="https://wordpress.org/plugins/taxjar-simplified-taxes-for-woocommerce/"
      if curl -sf "$PLUGIN_URL" | grep -q "$VERSION"; then
        echo "+++ Version $VERSION is live on WordPress.org"
      else
        echo "Version not yet visible (may take a few minutes)"
      fi

      echo "+++ Release Complete"
      echo "GitHub: https://github.com/taxjar/taxjar-woocommerce-plugin/releases/tag/$VERSION"
      echo "WordPress.org: $PLUGIN_URL"
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          always-pull: true
    timeout_in_minutes: 5
