# TaxJar WooCommerce Plugin CI Pipeline - Phase 1
# Quality gates for pull requests and releases

steps:
  # Stage 1: PHP Lint - Fast syntax validation
  - label: ":php: PHP Lint"
    key: "lint"
    command: |
      echo "+++ Checking PHP syntax"
      docker run --rm -v "$(pwd):/app" -w /app php:8.2-cli bash -c '
        find . -name "*.php" -not -path "./vendor/*" -not -path "./.buildkite/*" -print0 | \
          xargs -0 -n1 -P8 php -l
      '
    agents:
      queue: "docker"
    timeout_in_minutes: 5
    soft_fail: false

  # Validate version consistency in PRs
  - label: ":clipboard: Validate Version"
    key: "validate-version"
    depends_on: "lint"
    command: ".buildkite/scripts/release-tool validate-version"
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          mount-buildkite-agent: true
          always-pull: true
    timeout_in_minutes: 5
    soft_fail: true  # Don't block PRs on validation during initial rollout

  # Stage 2: PHPCS - WordPress Coding Standards
  - label: ":white_check_mark: PHPCS - WordPress Coding Standards"
    key: "phpcs"
    depends_on: "lint"
    command: |
      echo "+++ Running PHPCS with WordPress Coding Standards"
      docker run --rm -v "$(pwd):/app" -w /app php:8.2-cli bash -c '
        echo "--- Installing system dependencies"
        apt-get update -qq && apt-get install -y -qq \
          git \
          unzip \
          libzip-dev > /dev/null 2>&1
        docker-php-ext-install zip > /dev/null 2>&1

        echo "--- Configuring git"
        git config --global --add safe.directory /app

        echo "--- Installing Composer"
        if [ ! -f composer.phar ]; then
          curl -sS https://getcomposer.org/installer | php > /dev/null
        fi

        echo "--- Installing PHP dependencies"
        php composer.phar install --no-interaction --quiet

        echo "+++ Verifying PHPCS installation"
        vendor/bin/phpcs -i

        echo "+++ Running code standards check"
        vendor/bin/phpcs \
          --extensions=php \
          --ignore=vendor/,node_modules/,.buildkite/,tests/ \
          --report=full \
          --report-checkstyle=phpcs-report.xml \
          . || PHPCS_EXIT=$$?

        if [ "$${PHPCS_EXIT:-0}" -ne 0 ]; then
          echo "WARNING: Code standards issues found (soft fail enabled)"
          exit 0
        fi
      '
    agents:
      queue: "docker"
    timeout_in_minutes: 10
    soft_fail: true  # Don't block on coding standards initially
    artifact_paths:
      - "phpcs-report.xml"

  # Stage 3: PHPUnit Tests - Parallel execution with unique transaction IDs
  - label: ":test_tube: PHPUnit - WC {{matrix}}"
    key: "phpunit"
    depends_on: "lint"
    matrix:
      - "7.x"
      - "8.x"
      - "9.x"
      - "10.x"
    env:
      BUILDKITE_MATRIX: "{{matrix}}"
    agents:
      queue: "docker"
    timeout_in_minutes: 15
    soft_fail: false  # Fail build on test failures
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
    plugins:
      - docker-compose#v4.14.0:
          run: wordpress
          config: .buildkite/docker-compose.test.yml
          command: ["/test-scripts/set-test-env.sh"]
          rm: false  # Don't auto-remove container so we can capture logs
          environment:
            - BUILDKITE_MATRIX={{matrix}}
            - TAXJAR_API_TOKEN
            - BUILDKITE_ANALYTICS_TOKEN
      - artifacts#v1.9.0:
          upload:
            - ".buildkite/test-results/*.xml"
            - ".buildkite/test-results/*.log"
      - test-collector#v1.10.0:
          files: ".buildkite/test-results/*.xml"
          format: "junit"

  # Stage 4: Release trigger (master only)
  - label: ":rocket: Check Release"
    key: "check-release"
    depends_on:
      - "validate-version"
      - "phpunit"
    if: build.branch == "master"
    command: |
      .buildkite/scripts/release-tool detect-version

      if buildkite-agent meta-data exists "SKIP_RELEASE" 2>/dev/null; then
        echo "Version already deployed - skipping release"
        exit 0
      fi

      echo "+++ New version detected - adding release steps"
      cat <<'RELEASE_PIPELINE' | buildkite-agent pipeline upload
      steps:
        - label: ":github: Create GitHub Release"
          key: "github-release"
          command: |
            export VERSION=$$(buildkite-agent meta-data get "release-version")
            .buildkite/scripts/release-tool github-release
          agents:
            queue: docker
          plugins:
            - docker#v5.1.0:
                image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
                propagate-environment: true
                mount-buildkite-agent: true
                always-pull: true
                environment:
                  - GITHUB_TOKEN
          timeout_in_minutes: 10

        - wait

        - label: ":package: Deploy to WordPress.org"
          key: "svn-deploy"
          command: |
            export VERSION=$$(buildkite-agent meta-data get "release-version")
            .buildkite/scripts/release-tool svn-deploy
          agents:
            queue: docker
          plugins:
            - docker#v5.1.0:
                image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
                propagate-environment: true
                mount-buildkite-agent: true
                always-pull: true
                environment:
                  - WORDPRESS_SVN_USERNAME
                  - WORDPRESS_SVN_PASSWORD
          timeout_in_minutes: 15

        - wait

        - label: ":white_check_mark: Verify Release"
          key: "verify-release"
          command: |
            export VERSION=$$(buildkite-agent meta-data get "release-version")
            echo "--- Waiting for WordPress.org to update"
            sleep 30

            PLUGIN_URL="https://wordpress.org/plugins/taxjar-simplified-taxes-for-woocommerce/"
            if curl -sf "$$PLUGIN_URL" | grep -q "$$VERSION"; then
              echo "+++ Version $$VERSION is live on WordPress.org"
            else
              echo "Version not yet visible (may take a few minutes)"
            fi

            echo "+++ Release Complete"
            echo "GitHub: https://github.com/taxjar/taxjar-woocommerce-plugin/releases/tag/$$VERSION"
            echo "WordPress.org: $$PLUGIN_URL"
          agents:
            queue: docker
          plugins:
            - docker#v5.1.0:
                image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
                propagate-environment: true
                always-pull: true
          timeout_in_minutes: 5
      RELEASE_PIPELINE
    agents:
      queue: docker
    plugins:
      - docker#v5.1.0:
          image: 708017133719.dkr.ecr.us-east-1.amazonaws.com/taxjar/ops-tools:latest
          propagate-environment: true
          mount-buildkite-agent: true
          always-pull: true
    timeout_in_minutes: 5

